// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nmsxzfbacqnvkuwknczb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tc3h6ZmJhY3Fudmt1d2tuY3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTczNjAsImV4cCI6MjA2Nzg3MzM2MH0.seVDniqmd174BImsyCPuSH5BUZqRH91qExEBh3fBfFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Medication CRUD
type Medication = Database['public']['Tables']['medications']['Row'];
type MedicationInsert = Database['public']['Tables']['medications']['Insert'];
type MedicationUpdate = Database['public']['Tables']['medications']['Update'];

export async function getMedications(userId: string) {
  return supabase
    .from('medications')
    .select('*')
    .eq('user_id', userId)
    .order('start_date', { ascending: false });
}

export async function addMedication(medication: MedicationInsert) {
  return supabase
    .from('medications')
    .insert([medication]);
}

export async function updateMedication(id: string, updates: MedicationUpdate) {
  return supabase
    .from('medications')
    .update(updates)
    .eq('id', id);
}

export async function deleteMedication(id: string) {
  return supabase
    .from('medications')
    .delete()
    .eq('id', id);
}